/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers.index'
import { Route as SalesIndexRouteImport } from './routes/sales.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as DeliveriesIndexRouteImport } from './routes/deliveries.index'
import { Route as CylindersIndexRouteImport } from './routes/cylinders.index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as SuppliersNewRouteImport } from './routes/suppliers.new'
import { Route as SuppliersIdRouteImport } from './routes/suppliers.$id'
import { Route as SalesQuotationRouteImport } from './routes/sales.quotation'
import { Route as SalesNewRouteImport } from './routes/sales.new'
import { Route as SalesIdRouteImport } from './routes/sales.$id'
import { Route as ProductsNewRouteImport } from './routes/products.new'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as DeliveriesNewRouteImport } from './routes/deliveries.new'
import { Route as DeliveriesIdRouteImport } from './routes/deliveries.$id'
import { Route as CylindersNewRouteImport } from './routes/cylinders.new'
import { Route as CylindersIdRouteImport } from './routes/cylinders.$id'
import { Route as CustomersNewRouteImport } from './routes/customers.new'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as SuppliersIdEditRouteImport } from './routes/suppliers.$id.edit'
import { Route as ProductsIdEditRouteImport } from './routes/products.$id.edit'
import { Route as CustomersIdEditRouteImport } from './routes/customers.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesIndexRoute = DeliveriesIndexRouteImport.update({
  id: '/deliveries/',
  path: '/deliveries/',
  getParentRoute: () => rootRouteImport,
} as any)
const CylindersIndexRoute = CylindersIndexRouteImport.update({
  id: '/cylinders/',
  path: '/cylinders/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersNewRoute = SuppliersNewRouteImport.update({
  id: '/suppliers/new',
  path: '/suppliers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIdRoute = SuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesQuotationRoute = SalesQuotationRouteImport.update({
  id: '/sales/quotation',
  path: '/sales/quotation',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesNewRoute = SalesNewRouteImport.update({
  id: '/sales/new',
  path: '/sales/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIdRoute = SalesIdRouteImport.update({
  id: '/sales/$id',
  path: '/sales/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesNewRoute = DeliveriesNewRouteImport.update({
  id: '/deliveries/new',
  path: '/deliveries/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesIdRoute = DeliveriesIdRouteImport.update({
  id: '/deliveries/$id',
  path: '/deliveries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CylindersNewRoute = CylindersNewRouteImport.update({
  id: '/cylinders/new',
  path: '/cylinders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CylindersIdRoute = CylindersIdRouteImport.update({
  id: '/cylinders/$id',
  path: '/cylinders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIdEditRoute = SuppliersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SuppliersIdRoute,
} as any)
const ProductsIdEditRoute = ProductsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProductsIdRoute,
} as any)
const CustomersIdEditRoute = CustomersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CustomersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRoute
  '/login': typeof LoginRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/customers/new': typeof CustomersNewRoute
  '/cylinders/$id': typeof CylindersIdRoute
  '/cylinders/new': typeof CylindersNewRoute
  '/deliveries/$id': typeof DeliveriesIdRoute
  '/deliveries/new': typeof DeliveriesNewRoute
  '/products/$id': typeof ProductsIdRouteWithChildren
  '/products/new': typeof ProductsNewRoute
  '/sales/$id': typeof SalesIdRoute
  '/sales/new': typeof SalesNewRoute
  '/sales/quotation': typeof SalesQuotationRoute
  '/suppliers/$id': typeof SuppliersIdRouteWithChildren
  '/suppliers/new': typeof SuppliersNewRoute
  '/customers/': typeof CustomersIndexRoute
  '/cylinders/': typeof CylindersIndexRoute
  '/deliveries/': typeof DeliveriesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/products/$id/edit': typeof ProductsIdEditRoute
  '/suppliers/$id/edit': typeof SuppliersIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRoute
  '/login': typeof LoginRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/customers/new': typeof CustomersNewRoute
  '/cylinders/$id': typeof CylindersIdRoute
  '/cylinders/new': typeof CylindersNewRoute
  '/deliveries/$id': typeof DeliveriesIdRoute
  '/deliveries/new': typeof DeliveriesNewRoute
  '/products/$id': typeof ProductsIdRouteWithChildren
  '/products/new': typeof ProductsNewRoute
  '/sales/$id': typeof SalesIdRoute
  '/sales/new': typeof SalesNewRoute
  '/sales/quotation': typeof SalesQuotationRoute
  '/suppliers/$id': typeof SuppliersIdRouteWithChildren
  '/suppliers/new': typeof SuppliersNewRoute
  '/customers': typeof CustomersIndexRoute
  '/cylinders': typeof CylindersIndexRoute
  '/deliveries': typeof DeliveriesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/sales': typeof SalesIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/products/$id/edit': typeof ProductsIdEditRoute
  '/suppliers/$id/edit': typeof SuppliersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRoute
  '/login': typeof LoginRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/customers/new': typeof CustomersNewRoute
  '/cylinders/$id': typeof CylindersIdRoute
  '/cylinders/new': typeof CylindersNewRoute
  '/deliveries/$id': typeof DeliveriesIdRoute
  '/deliveries/new': typeof DeliveriesNewRoute
  '/products/$id': typeof ProductsIdRouteWithChildren
  '/products/new': typeof ProductsNewRoute
  '/sales/$id': typeof SalesIdRoute
  '/sales/new': typeof SalesNewRoute
  '/sales/quotation': typeof SalesQuotationRoute
  '/suppliers/$id': typeof SuppliersIdRouteWithChildren
  '/suppliers/new': typeof SuppliersNewRoute
  '/customers/': typeof CustomersIndexRoute
  '/cylinders/': typeof CylindersIndexRoute
  '/deliveries/': typeof DeliveriesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/products/$id/edit': typeof ProductsIdEditRoute
  '/suppliers/$id/edit': typeof SuppliersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/expenses'
    | '/login'
    | '/customers/$id'
    | '/customers/new'
    | '/cylinders/$id'
    | '/cylinders/new'
    | '/deliveries/$id'
    | '/deliveries/new'
    | '/products/$id'
    | '/products/new'
    | '/sales/$id'
    | '/sales/new'
    | '/sales/quotation'
    | '/suppliers/$id'
    | '/suppliers/new'
    | '/customers/'
    | '/cylinders/'
    | '/deliveries/'
    | '/products/'
    | '/sales/'
    | '/suppliers/'
    | '/customers/$id/edit'
    | '/products/$id/edit'
    | '/suppliers/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/expenses'
    | '/login'
    | '/customers/$id'
    | '/customers/new'
    | '/cylinders/$id'
    | '/cylinders/new'
    | '/deliveries/$id'
    | '/deliveries/new'
    | '/products/$id'
    | '/products/new'
    | '/sales/$id'
    | '/sales/new'
    | '/sales/quotation'
    | '/suppliers/$id'
    | '/suppliers/new'
    | '/customers'
    | '/cylinders'
    | '/deliveries'
    | '/products'
    | '/sales'
    | '/suppliers'
    | '/customers/$id/edit'
    | '/products/$id/edit'
    | '/suppliers/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/expenses'
    | '/login'
    | '/customers/$id'
    | '/customers/new'
    | '/cylinders/$id'
    | '/cylinders/new'
    | '/deliveries/$id'
    | '/deliveries/new'
    | '/products/$id'
    | '/products/new'
    | '/sales/$id'
    | '/sales/new'
    | '/sales/quotation'
    | '/suppliers/$id'
    | '/suppliers/new'
    | '/customers/'
    | '/cylinders/'
    | '/deliveries/'
    | '/products/'
    | '/sales/'
    | '/suppliers/'
    | '/customers/$id/edit'
    | '/products/$id/edit'
    | '/suppliers/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpensesRoute: typeof ExpensesRoute
  LoginRoute: typeof LoginRoute
  CustomersIdRoute: typeof CustomersIdRouteWithChildren
  CustomersNewRoute: typeof CustomersNewRoute
  CylindersIdRoute: typeof CylindersIdRoute
  CylindersNewRoute: typeof CylindersNewRoute
  DeliveriesIdRoute: typeof DeliveriesIdRoute
  DeliveriesNewRoute: typeof DeliveriesNewRoute
  ProductsIdRoute: typeof ProductsIdRouteWithChildren
  ProductsNewRoute: typeof ProductsNewRoute
  SalesIdRoute: typeof SalesIdRoute
  SalesNewRoute: typeof SalesNewRoute
  SalesQuotationRoute: typeof SalesQuotationRoute
  SuppliersIdRoute: typeof SuppliersIdRouteWithChildren
  SuppliersNewRoute: typeof SuppliersNewRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  CylindersIndexRoute: typeof CylindersIndexRoute
  DeliveriesIndexRoute: typeof DeliveriesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries/': {
      id: '/deliveries/'
      path: '/deliveries'
      fullPath: '/deliveries/'
      preLoaderRoute: typeof DeliveriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cylinders/': {
      id: '/cylinders/'
      path: '/cylinders'
      fullPath: '/cylinders/'
      preLoaderRoute: typeof CylindersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/new': {
      id: '/suppliers/new'
      path: '/suppliers/new'
      fullPath: '/suppliers/new'
      preLoaderRoute: typeof SuppliersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$id': {
      id: '/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof SuppliersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/quotation': {
      id: '/sales/quotation'
      path: '/sales/quotation'
      fullPath: '/sales/quotation'
      preLoaderRoute: typeof SalesQuotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/new': {
      id: '/sales/new'
      path: '/sales/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof SalesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/$id': {
      id: '/sales/$id'
      path: '/sales/$id'
      fullPath: '/sales/$id'
      preLoaderRoute: typeof SalesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/new': {
      id: '/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries/new': {
      id: '/deliveries/new'
      path: '/deliveries/new'
      fullPath: '/deliveries/new'
      preLoaderRoute: typeof DeliveriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries/$id': {
      id: '/deliveries/$id'
      path: '/deliveries/$id'
      fullPath: '/deliveries/$id'
      preLoaderRoute: typeof DeliveriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cylinders/new': {
      id: '/cylinders/new'
      path: '/cylinders/new'
      fullPath: '/cylinders/new'
      preLoaderRoute: typeof CylindersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cylinders/$id': {
      id: '/cylinders/$id'
      path: '/cylinders/$id'
      fullPath: '/cylinders/$id'
      preLoaderRoute: typeof CylindersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$id/edit': {
      id: '/suppliers/$id/edit'
      path: '/edit'
      fullPath: '/suppliers/$id/edit'
      preLoaderRoute: typeof SuppliersIdEditRouteImport
      parentRoute: typeof SuppliersIdRoute
    }
    '/products/$id/edit': {
      id: '/products/$id/edit'
      path: '/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof ProductsIdEditRouteImport
      parentRoute: typeof ProductsIdRoute
    }
    '/customers/$id/edit': {
      id: '/customers/$id/edit'
      path: '/edit'
      fullPath: '/customers/$id/edit'
      preLoaderRoute: typeof CustomersIdEditRouteImport
      parentRoute: typeof CustomersIdRoute
    }
  }
}

interface CustomersIdRouteChildren {
  CustomersIdEditRoute: typeof CustomersIdEditRoute
}

const CustomersIdRouteChildren: CustomersIdRouteChildren = {
  CustomersIdEditRoute: CustomersIdEditRoute,
}

const CustomersIdRouteWithChildren = CustomersIdRoute._addFileChildren(
  CustomersIdRouteChildren,
)

interface ProductsIdRouteChildren {
  ProductsIdEditRoute: typeof ProductsIdEditRoute
}

const ProductsIdRouteChildren: ProductsIdRouteChildren = {
  ProductsIdEditRoute: ProductsIdEditRoute,
}

const ProductsIdRouteWithChildren = ProductsIdRoute._addFileChildren(
  ProductsIdRouteChildren,
)

interface SuppliersIdRouteChildren {
  SuppliersIdEditRoute: typeof SuppliersIdEditRoute
}

const SuppliersIdRouteChildren: SuppliersIdRouteChildren = {
  SuppliersIdEditRoute: SuppliersIdEditRoute,
}

const SuppliersIdRouteWithChildren = SuppliersIdRoute._addFileChildren(
  SuppliersIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpensesRoute: ExpensesRoute,
  LoginRoute: LoginRoute,
  CustomersIdRoute: CustomersIdRouteWithChildren,
  CustomersNewRoute: CustomersNewRoute,
  CylindersIdRoute: CylindersIdRoute,
  CylindersNewRoute: CylindersNewRoute,
  DeliveriesIdRoute: DeliveriesIdRoute,
  DeliveriesNewRoute: DeliveriesNewRoute,
  ProductsIdRoute: ProductsIdRouteWithChildren,
  ProductsNewRoute: ProductsNewRoute,
  SalesIdRoute: SalesIdRoute,
  SalesNewRoute: SalesNewRoute,
  SalesQuotationRoute: SalesQuotationRoute,
  SuppliersIdRoute: SuppliersIdRouteWithChildren,
  SuppliersNewRoute: SuppliersNewRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  CylindersIndexRoute: CylindersIndexRoute,
  DeliveriesIndexRoute: DeliveriesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
